### ISSUE TITLE
glove files

### ISSUE THREAD

**Issue by yassmine-lam** [LingxB/atlx#8]
Hi,

thank u for sharing ur code with us
can u provide us with the script to generate these two files using another embedding models 
glove_lookup.parquet
glove_symdict.yml
?

thank u

**Comment by LingxB** [comment]
Hi there,

I was not able to recover the files for generating these embedding files, however they are not hard to reproduce. 

The `glove_symdict.yml` is essentially the vocabulary of the model, with key as token and value as row index of the embedding matrix. To use other embeddings, you can simplly generate a embedding file (`glove_lookup.parquet`) according to the vocabulary. 

The `glove_lookup.parquet` is the table (pandas dataframe) of embeddings, with key as token and columns as embeddings. 

Best!
LB
